name: Security Scan

on:
  pull_request:
    branches: [main]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      security-events: write
      pull-requests: write
    
    steps:
      - name: Run Fraim Security Scan
        id: fraim-scan
        uses: fraim-dev/fraim-action@a89c4d378dd9e6bb36d6a84af0251e61ee7dea11
        with:
          gemini-api-key: ${{ secrets.GEMINI_API_KEY }}
